import os

def write_f(path, content):
    with open(path, "w", encoding="utf-8") as f:
        f.write(content.strip())

# --- TRUSHKIN (macOS Sonoma Light, Corporate, Russian, Index notation) ---
base_2 = "src/2_trushkin_macbus/Методы оптимизации"

p1_model_2 = """
Create a highly detailed, extremely realistic, full-screen screenshot of Microsoft Excel running on a macOS Sonoma desktop. 
The operating system theme is Light mode. The window has standard macOS traffic light buttons (red, yellow, green) in the top left corner.
The Excel interface is completely localized in Russian. The "Home" (Главная) ribbon tab is currently active. 
The visual style of the spreadsheet is "Corporate": headers are a dark navy blue (Hex: #1F4E78) with bold, white font; input cells have a very light gray background (#F2F2F2) with solid black borders; the target function cell is shaded in a soft light blue (#DDEBF7). 

The spreadsheet is displaying a linear programming model for agricultural optimization (Variant 1.5 - Corn and Soy). 
The layout of the model is vertical. 
At the top, cells C2 and D2 are labeled "x1 (Кукуруза)" and "x2 (Соя)". Below them, cells C3 and D3 show the current values: 0 and 0.
Below that, cell C5 reads "Прибыль (ден. ед.)", and cell D5 contains the Excel formula =СУММПРОИЗВ(C3:D3; C6:D6). The coefficients 90 and 360 are entered in C6 and D6.
Further down is the constraints block. Column E shows the calculated Left Hand Side (LHS) using =СУММПРОИЗВ. Column F shows the inequality signs (<=). Column G shows the Right Hand Side (RHS) limits: 400, 60000, and 21000.
The image must focus on absolute clarity of the text and the strict, professional corporate layout of the table cells without any desktop icons visible in the background.
"""
write_f(f"{base_2}/ЛР_1/source/prompt_excel_1_1_model.txt", p1_model_2)

p1_solver_2 = """
Create a high-resolution screenshot focusing on the Microsoft Excel "Поиск решения" (Solver) dialog box floating over a blurred spreadsheet background.
The operating system is macOS Sonoma with the Light theme active. The dialog box has the classic macOS top bar with a drop shadow.
The interface of the Solver add-in is entirely in Russian.

The contents of the "Поиск решения" dialog box are meticulously filled out for a linear programming maximization problem (Variant 1.5):
- The field "Оптимизировать целевую функцию:" contains the reference to the target cell, e.g., $D$5.
- The radio button "Максимум" (Maximize) is selected.
- The field "Изменяя ячейки переменных:" contains the range $C$3:$D$3.
- The "В соответствии с ограничениями:" list box displays three distinct constraints:
  $E$9 <= $G$9
  $E$10 <= $G$10
  $E$11 <= $G$11
- There is a checked checkbox next to "Сделать переменные без ограничений неотрицательными" (Make Unconstrained Variables Non-Negative).
- The dropdown menu "Выберите метод решения:" is expanded or showing the option "Поиск решения линейных задач симплекс-методом" (Simplex LP).

The lighting and resolution must make the text inside the dialog box incredibly sharp, simulating an actual working session of an engineering student.
"""
write_f(f"{base_2}/ЛР_1/source/prompt_excel_1_1_solver.txt", p1_solver_2)

p1_result_2 = """
Create a full-screen, ultra-sharp screenshot of Microsoft Excel on a macOS Sonoma desktop (Light theme). 
The spreadsheet displays the successfully solved optimization model for Variant 1.5 (Farmer's crop distribution).
The table strictly adheres to the "Corporate" visual style: navy blue headers (#1F4E78), white text for headers, light gray input cells (#F2F2F2), and a pale blue target cell (#DDEBF7). All cells have thin, black, crisp borders.

The key difference from the initial model is that the Solver has completed its run. 
The input cells for the variables x1 (Кукуруза) and x2 (Соя) in cells C3 and D3 now display the optimal mathematical solution values instead of zeros (e.g., specific integer or decimal numbers calculated by the Simplex algorithm).
The target cell (D5), which contains the =СУММПРОИЗВ() formula, now displays the maximized total revenue, a large numerical value.
In the constraints block (rows 9, 10, and 11), the calculated Left Hand Side (LHS) values in column E have updated to reflect the resource consumption, and they clearly do not exceed the Right Hand Side (RHS) limits shown in column G (400, 60000, 21000).

The interface is completely in Russian, emphasizing an academic, formal engineering environment. No background distractions.
"""
write_f(f"{base_2}/ЛР_1/source/prompt_excel_1_1_result.txt", p1_result_2)

p1_sens_2 = """
Create a highly realistic screenshot of a Microsoft Excel "Отчет по устойчивости" (Sensitivity Report) generated by the Solver add-in.
The environment is macOS Sonoma, Light theme. The application is full-screen, and the language is Russian.
The report is formatted automatically by Excel: it has a clean, minimalist layout with standard black text on a white background, without heavy cell shading, typical of auto-generated analytical reports.

The sheet is divided into two main tables:
1. "Ячейки переменных" (Variable Cells): Columns include "Ячейка" (Cell), "Имя" (Name), "Результирующее значение" (Final Value), "Нормированная стоимость" (Reduced Cost), "Целевой коэффициент" (Objective Coefficient), "Допустимое увеличение" (Allowable Increase), and "Допустимое уменьшение" (Allowable Decrease). The data rows correspond to the variables x1 and x2.
2. "Ограничения" (Constraints): Columns include "Ячейка" (Cell), "Имя" (Name), "Результирующее значение" (Final Value), "Теневая цена" (Shadow Price), "Ограничение правая часть" (Constraint R.H. Side), "Допустимое увеличение", and "Допустимое уменьшение". The rows list the resources (Земля, Ссуда, Склад). 

At least one of the "Теневая цена" (Shadow Price) values is a non-zero positive number, indicating a scarce resource. The typography must be legible, simulating a real academic analysis tool.
"""
write_f(f"{base_2}/ЛР_1/source/prompt_excel_1_2_sensitivity.txt", p1_sens_2)

p2_result_2 = """
Generate a full-screen screenshot of Microsoft Excel running on a macOS Sonoma operating system with the Light theme enabled.
The spreadsheet contains the solved optimization model for Variant 1.5 (Dairy plant production of milk, kefir, and sour cream).
The interface language is Russian. The visual formatting follows a strict "Corporate" style: dark blue column headers with bold white font, light gray input cells, and a soft blue target cell representing the maximized profit.

The layout is vertical. The variables (x1, x2, x3) are positioned at the top of the sheet. Since the Solver algorithm has already been executed, the input cells contain the final, optimal numerical values representing the tonnage of each dairy product to be produced.
The target cell clearly shows the maximum achievable profit calculated using the =СУММПРОИЗВ() function.
Below, the constraints matrix includes rows for Raw Milk, Equipment hours, Sour Cream Automata hours, and the mandatory minimum milk production plan. 
The "Fact" (Left Hand Side) column dynamically reflects the resource usage based on the optimal production plan, explicitly adhering to the <= and >= signs compared to the "Limit" (Right Hand Side) column.
The screenshot must convey a professional, formal engineering analysis setting without any unrelated UI elements.
"""
write_f(f"{base_2}/ЛР_2/source/prompt_excel_2_1_result.txt", p2_result_2)

p2_matrix_2 = """
Create a precise, high-resolution screenshot of a Microsoft Excel spreadsheet on macOS Sonoma (Light theme) showing the initial setup for a Transportation Problem (Variant 2.5).
The interface is entirely in Russian. The visual style is "Corporate" with dark navy blue headers (#1F4E78) and distinct black borders separating all data cells.

The spreadsheet prominently features a 3x5 cost matrix. The row headers are labeled A1, A2, and A3 (representing supply quarries). The column headers are B1, B2, B3, B4, B5 (representing demand sites). Inside the matrix, specific transportation costs per unit are filled in (e.g., 3, 4, 5, 15, 24 for the first row).
Directly below or adjacent to the cost matrix is a structurally identical "Shipment Matrix" for the variables, currently filled with zeros.
On the right edge of the Shipment Matrix, there is a column calculating the Row Sums (using the =СУММ() formula), followed by an "=" sign column, and the Supply limits (15, 15, 15).
At the bottom edge of the Shipment Matrix, there is a row calculating the Column Sums, followed by an "=" sign row, and the Demand requirements (11, 11, 11, 16, 11).
A dedicated cell for "Total Cost" (Общая стоимость) is visible, containing the formula =СУММПРОИЗВ() linking the cost matrix and the shipment matrix. The image must look exceptionally structured and academic.
"""
write_f(f"{base_2}/ЛР_2/source/prompt_excel_2_2_matrix.txt", p2_matrix_2)

p2_solver_2 = """
Generate a highly detailed screenshot of the "Поиск решения" (Solver) dialog box in Microsoft Excel on a macOS Sonoma desktop (Light theme).
The dialog is hovering over the transportation problem spreadsheet (Variant 2.5). The application language is Russian.

The Solver parameters are meticulously configured for a complex logistics network:
- "Оптимизировать целевую функцию:" points to the Total Cost cell.
- The "Минимум" (Minimize) radio button is actively selected.
- "Изменяя ячейки переменных:" points to the entire 3x5 block of the Shipment Matrix.
- The constraints list ("В соответствии с ограничениями:") is extensive and specific. It contains at least two visible multi-cell constraints:
  1. A constraint ensuring that the range of Row Sums is exactly equal (=) to the range of Supply limits.
  2. A constraint ensuring that the range of Column Sums is exactly equal (=) to the range of Demand requirements.
  3. An additional, manual constraint: e.g., $C$15 <= 3, reflecting a specific route restriction.
- The checkbox for non-negative variables is checked.
- The solving method is set to "Поиск решения линейных задач симплекс-методом".

The text rendering must be flawless, mimicking a real Retina display output of an engineer setting up a routing optimization task.
"""
write_f(f"{base_2}/ЛР_2/source/prompt_excel_2_2_solver.txt", p2_solver_2)


# --- NOVOSELZ (Windows 11 Dark, Minimalist, English, Alphabet notation) ---
base_3 = "src/3_novoselz_drum/Методы оптимизации"

p1_model_3 = """
Create a full-screen, ultra-realistic screenshot of Microsoft Excel running on a Windows 11 desktop with Dark Mode enabled.
The application interface, including the ribbon, menus, and window borders, is entirely in English and features the modern Windows 11 dark gray/black aesthetics.
The visual style of the spreadsheet cells is strictly "Minimalist": there are absolutely no background color fills (no shading). The structure is defined solely by crisp, black cell borders and bold Arial font for headers.

The spreadsheet illustrates a linear programming model (Variant 1.3 - Factory Details X and Y). 
Crucially, the layout is horizontal. On the left side of the screen, the variable cells are laid out in a column, labeled with simple alphabetical notation: 'x' (for Details X) and 'y' (for Details Y). Next to them are the input cells, currently set to initial values (e.g., 600 and 0).
On the right side of the screen, the Objective function and Constraints are constructed. A cell titled "Revenue" contains the English formula =SUMPRODUCT(). 
Below it, the constraints matrix is laid out, featuring columns for "LHS" (Left Hand Side calculated via formulas), "Sign" (<=, >=), and "RHS" (Right Hand Side limits like 4000, 2250, 10000).
The screenshot must convey a highly technical, bare-bones, data-driven environment typical of an advanced user keeping a technical diary. No desktop clutter.
"""
write_f(f"{base_3}/ЛР_1/source/prompt_excel_1_1_model.txt", p1_model_3)

p1_solver_3 = """
Generate a high-definition screenshot focusing on the Microsoft Excel "Solver Parameters" dialog box on a Windows 11 Dark Mode operating system.
The Excel interface language is strictly English. The dialog box has the distinctive square corners and dark title bar of Windows 11.

The contents of the "Solver Parameters" dialog box are actively filled with data for optimizing a factory production line (Variant 1.3):
- "Set Objective:" points to the Revenue cell.
- The radio button "Max" is selected.
- "By Changing Variable Cells:" indicates the cells for variables x and y.
- The "Subject to the Constraints:" box is populated with multiple rules, reflecting complex factory conditions:
  - LHS range <= RHS range (for resources like labor and metals).
  - A specific limit like $C$3 <= 2250 (Max capacity for X).
  - A specific minimum like $C$3 >= 600 (Order commitment).
  - A sum minimum like $C$3 + $C$4 >= 1500 (Union agreement).
- "Make Unconstrained Variables Non-Negative" is checked.
- "Select Solving Method:" is set to "Simplex LP".

The background should show the minimalist, uncolored spreadsheet grid slightly out of focus. The text inside the dialog must be perfectly legible and antialiased.
"""
write_f(f"{base_3}/ЛР_1/source/prompt_excel_1_1_solver.txt", p1_solver_3)

p1_result_3 = """
Create a highly detailed, full-screen screenshot of Microsoft Excel on a Windows 11 Dark Mode desktop.
The spreadsheet displays the solved optimization model for the factory production scenario (Variant 1.3).
The interface is in English. The spreadsheet styling remains strictly "Minimalist" — pure black borders on a white grid, utilizing Arial font, with zero background color fills.

The horizontal layout shows that the Solver has successfully executed. 
The variable cells for 'x' and 'y' on the left now display the optimal integer values that maximize the factory's income, rather than their starting values.
On the right side, the target cell ("Revenue"), driven by the =SUMPRODUCT() formula, displays the maximized financial output.
The "LHS" column in the constraints section has updated automatically. It clearly demonstrates that the resource consumption numbers are tightly pressed against or exactly equal to some of the "RHS" limits (e.g., hitting the 4000 labor hours cap), visually proving the optimization.
The overall aesthetic must reflect a serious, distraction-free technical workspace.
"""
write_f(f"{base_3}/ЛР_1/source/prompt_excel_1_1_result.txt", p1_result_3)

p1_sens_3 = """
Create a precise screenshot of an auto-generated "Sensitivity Report" sheet in Microsoft Excel.
The environment is Windows 11 Dark Mode. The application language is English.
The report is presented in its default, unstyled format (black text, standard gridlines, no custom formatting), reflecting the raw output of the Solver add-in.

The report contains two distinct tables:
1. "Variable Cells": This table lists the variables 'x' and 'y', showing their "Final Value", "Reduced Cost", "Objective Coefficient", "Allowable Increase", and "Allowable Decrease".
2. "Constraints": This table lists the various factory limitations (Labor, Metal, Orders). The columns include "Final Value", "Shadow Price", "Constraint R.H. Side", "Allowable Increase", and "Allowable Decrease".

Crucially, the "Shadow Price" column must contain at least one positive value (e.g., indicating the marginal value of an extra hour of labor or kg of metal), and the "Final Value" must align with the constraints. The text must be crisp, embodying a technical, analytical artifact.
"""
write_f(f"{base_3}/ЛР_1/source/prompt_excel_1_2_sensitivity.txt", p1_sens_3)

p2_result_3 = """
Generate a full-screen, high-resolution screenshot of Microsoft Excel running on Windows 11 Dark Mode.
The sheet displays a successfully solved broiler ration optimization problem (Variant 1.3).
The language is English. The styling is strictly "Minimalist" (no cell shading, black gridlines only).

The layout is horizontal. The variables representing different feed ingredients ('x' for Limestone, 'y' for Grain, 'z' for Soybeans) are arranged in a column on the left, displaying their optimal calculated weights in kilograms (e.g., real decimal values).
To the right, the objective function cell, calculating the total cost using =SUMPRODUCT(), displays the minimized monetary value.
Below or adjacent to it, the constraints matrix shows the nutritional requirements (Calcium, Protein, Fiber). The "LHS" column shows the exact percentages achieved in the optimal mix, directly compared to the "RHS" column constraints (e.g., Protein >= 22%).
The image should look like a snapshot from an engineer's technical diary, focused purely on data and mathematical results.
"""
write_f(f"{base_3}/ЛР_2/source/prompt_excel_2_1_result.txt", p2_result_3)

p2_matrix_3 = """
Create a meticulously detailed screenshot of a Microsoft Excel spreadsheet on Windows 11 Dark Mode.
The interface is in English. The spreadsheet shows the initial setup for a 3x5 Transportation Problem (Variant 2.3).
The style is "Minimalist" — stark black borders, no background shading, purely structural formatting.

The sheet prominently features a "Cost Matrix" with rows A1, A2, A3 and columns B1 through B5, filled with specific integer shipping tariffs.
Nearby, an identically structured "Shipment Matrix" is created for the changing variables, currently populated with zeros.
Formulas are set up on the peripheries of the Shipment Matrix:
- A column on the right uses the =SUM() function to calculate the total shipped from each row, placed next to an "=" sign and the Supply limits (60, 90, 140).
- A row at the bottom uses the =SUM() function to calculate the total received by each column, placed above an "=" sign and the Demand requirements (40, 30, 90, 80, 50).
A target cell labeled "Total Cost" contains the =SUMPRODUCT() formula, linking the Cost and Shipment matrices. The visual tone is highly analytical and clean.
"""
write_f(f"{base_3}/ЛР_2/source/prompt_excel_2_2_matrix.txt", p2_matrix_3)

p2_solver_3 = """
Generate a highly realistic screenshot of the "Solver Parameters" dialog box in Microsoft Excel on Windows 11 Dark Mode.
The dialog is positioned over the minimalist transportation problem spreadsheet. The interface is entirely in English.

The dialog box settings are rigorously defined for routing optimization:
- "Set Objective:" points to the cell calculating Total Cost.
- The "Min" (Minimize) radio button is selected.
- "By Changing Variable Cells:" indicates the absolute cell references for the 3x5 Shipment Matrix block.
- "Subject to the Constraints:" lists the necessary balancing equations:
  - The range of row sums exactly equals (=) the range of Supply values.
  - The range of column sums exactly equals (=) the range of Demand values.
  - There is a specific, manually added constraint visible in the list: e.g., $D$15 <= 3, simulating a traffic bottleneck on a specific route.
- "Make Unconstrained Variables Non-Negative" is enabled.
- "Select Solving Method:" is "Simplex LP".

The screenshot must prioritize the sharp, clear rendering of the English text within the Windows 11 UI components.
"""
write_f(f"{base_3}/ЛР_2/source/prompt_excel_2_2_solver.txt", p2_solver_3)


# --- VELIEV (macOS Sequoia Dark, Colorful, Russian, Semantic notation) ---
base_4 = "src/4_veliev_macbook/Методы оптимизации"

p1_model_4 = """
Create a stunning, high-resolution full-screen screenshot of Microsoft Excel running on a macOS Sequoia 15.0 desktop.
The operating system is in Dark Mode, featuring the "Sequoia Dynamic Dark" wallpaper subtly visible if Excel isn't fully maximized. 
The Excel interface itself is fully localized in Russian.
The spreadsheet design utilizes a highly "Colorful" and ergonomic visual style:
- The input variable cells are shaded in a bright, noticeable yellow (#FFFF00).
- The target function cell (Objective) is highlighted in a vibrant green (#92D050).
- The entire block of constraint cells (LHS, Signs, RHS) is shaded in a warm orange (#FFC000).
- Headers use bold text.

The spreadsheet displays a linear programming model for paint production (Variant 1.2). 
The layout is strictly vertical. 
At the top, the variables are named using semantic notation: Q_ext (Наружная) and Q_int (Внутренняя). The yellow input cells below them show initial values of 0.
The green target cell below is labeled "Доход (руб.)" and contains the formula =СУММПРОИЗВ(). 
At the bottom, the orange constraints matrix defines limits for "Продукт А", "Продукт В", and specific market demand rules (<= 6, <= 8, <= 1, <= 2).
The image must capture the vibrant, color-coded workflow typical of an advanced user organizing complex data.
"""
write_f(f"{base_4}/ЛР_1/source/prompt_excel_1_1_model.txt", p1_model_4)

p1_solver_4 = """
Generate a highly detailed screenshot of the "Поиск решения" (Solver) dialog box floating above a colorful Excel spreadsheet on a macOS Sequoia Dark Mode desktop.
The Excel interface is in Russian. The macOS window controls (red, yellow, green dots) are visible in the top left of the main window.

The dialog box is completely configured for the paint production maximization problem (Variant 1.2):
- "Оптимизировать целевую функцию:" points to the green target cell reference.
- "Максимум" is selected.
- "Изменяя ячейки переменных:" points to the yellow input cells range.
- "В соответствии с ограничениями:" displays a list of constraints where the calculated LHS cells are restricted by the RHS cells (e.g., $E$10 <= $G$10, and specific demand constraints like $E$12 <= 1, $E$13 <= 2).
- The non-negativity checkbox is active.
- The method is set to "Поиск решения линейных задач симплекс-методом".

The text rendering within the dialog box must be crystal clear and highly legible against the dark mode UI of macOS Sequoia.
"""
write_f(f"{base_4}/ЛР_1/source/prompt_excel_1_1_solver.txt", p1_solver_4)

p1_result_4 = """
Create a full-screen, vibrant screenshot of Microsoft Excel on a macOS Sequoia Dark Mode operating system.
The spreadsheet displays the optimal solution for the paint production model (Variant 1.2).
The language is Russian. The formatting retains its strong "Colorful" aesthetic: yellow variable cells, a green target cell, and orange constraint cells.

The Solver has finished its execution. 
The yellow cells for the semantic variables Q_ext and Q_int now display the optimal calculated production volumes (real numbers) instead of zeros.
The green target cell, driven by the =СУММПРОИЗВ() function, showcases the absolute maximum revenue achievable under the given conditions.
In the orange constraints block, the calculated values in the "Факт" (Fact/LHS) column reflect the exact resource consumption, clearly demonstrating that no limits (6, 8, 1, 2) in the "Лимит" (Limit/RHS) column have been exceeded. 
The image must perfectly blend the dark UI of the macOS framework with the brightly colored, solved Excel matrix.
"""
write_f(f"{base_4}/ЛР_1/source/prompt_excel_1_1_result.txt", p1_result_4)

p1_sens_4 = """
Create a high-fidelity screenshot of the "Отчет по устойчивости" (Sensitivity Report) sheet in Microsoft Excel on macOS Sequoia Dark Mode.
The interface is entirely in Russian. 
While Excel auto-generates this report, the screenshot should show the user has applied the "Colorful" theme to the report headers: the "Ячейки переменных" and "Ограничения" table headers might have a subtle colored fill to maintain consistency with the user's advanced aesthetic.

The tables display comprehensive sensitivity data for the paint production problem. 
The variables section lists Q_ext and Q_int with their Final Values and Objective Coefficients.
The constraints section lists the resources (Продукт А, Продукт В, Спрос). It explicitly displays the "Теневая цена" (Shadow Price) for each constraint, showing positive values for bottlenecks and zeros for abundant resources. The Allowable Increase and Decrease columns are fully populated. The visual output must be sharp, simulating a professional data analysis environment.
"""
write_f(f"{base_4}/ЛР_1/source/prompt_excel_1_2_sensitivity.txt", p1_sens_4)

p2_result_4 = """
Generate a full-screen screenshot of a solved Microsoft Excel optimization model on macOS Sequoia Dark Mode.
The spreadsheet solves the metallurgical coal mixture problem (Variant 1.2).
The language is Russian. The visual style is aggressively "Colorful" for maximum readability: yellow input parameters, a vibrant green target cell, and an orange constraints block.

The layout is vertical. The semantic variables P_a, P_b, P_c (representing the proportion of coal sorts A, B, C) are located in the yellow cells at the top, displaying their optimal calculated decimal fractions.
The green target cell uses =СУММПРОИЗВ() and displays the strictly minimized cost of the coal mixture.
The orange constraints section below verifies the nutritional/chemical limits. The "Факт" column shows the calculated percentages of Phosphorus and Ash, precisely matching or staying strictly below the rigid constraints (<= 0.03% and <= 3.25%) shown in the "Лимит" column. The sum of the fractions (P_a + P_b + P_c) perfectly equals 1.
The image must look highly professional, combining vivid data visualization with a dark OS theme.
"""
write_f(f"{base_4}/ЛР_2/source/prompt_excel_2_1_result.txt", p2_result_4)

p2_matrix_4 = """
Create a stunning, high-resolution screenshot of a Microsoft Excel spreadsheet on macOS Sequoia Dark Mode.
The interface is in Russian. The sheet shows the complex setup for a 3x5 Transportation Problem (Variant 2.2).
The "Colorful" formatting is actively used to define the logical zones of the matrix:
- The 3x5 Cost Matrix (Тарифы) has light blue headers.
- The 3x5 Shipment Matrix (Объемы перевозок) has its inner variable cells filled with bright yellow (#FFFF00).
- The row calculating total shipments and the column calculating total receipts are highlighted in orange, showing the =СУММ() formulas.
- The Supply (Предложение) limits (500, 300, 100) and Demand (Потребности) limits (150, 350, 200, 100, 100) are highlighted in a contrasting color.
- The grand "Total Cost" (Общая стоимость) cell is highlighted in bright green.

The screenshot captures an advanced user's perfectly organized workspace before the Solver algorithm is executed, with all variable cells in the yellow matrix currently set to zero.
"""
write_f(f"{base_4}/ЛР_2/source/prompt_excel_2_2_matrix.txt", p2_matrix_4)

p2_solver_4 = """
Generate a highly detailed screenshot of the "Поиск решения" (Solver) dialog box floating above a colorful transportation matrix in Microsoft Excel.
The operating system is macOS Sequoia Dark Mode. The Excel language is Russian.

The dialog box is meticulously configured for the logistics routing problem:
- "Оптимизировать целевую функцию:" points to the green Total Cost cell.
- The "Минимум" (Minimize) option is selected.
- "Изменяя ячейки переменных:" targets the entire yellow 3x5 block of the Shipment Matrix.
- "В соответствии с ограничениями:" shows the balancing rules:
  - The range of calculated row sums equals (=) the range of Supply limits.
  - The range of calculated column sums equals (=) the range of Demand limits.
  - An additional, manual constraint like $D$15 <= 3 is clearly visible, representing a blocked or limited road segment.
- The Simplex LP ("Поиск решения линейных задач симплекс-методом") is chosen from the dropdown.

The visual clarity of the Russian text in the dark mode UI must be absolute, emphasizing the precision of the optimization setup.
"""
write_f(f"{base_4}/ЛР_2/source/prompt_excel_2_2_solver.txt", p2_solver_4)
